# -*- coding: utf-8 -*-
"""rpsai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uU6hXulAb_2vFU0f8WkpklS0GJfXdKyw
"""

# Rock Paper Scissors Plus - AI Referee (Colab Version)

import random

# Game state
state = {
    "round": 1,
    "user": 0,
    "bot": 0,
    "userbomb": False,
    "botbomb": False
}

moves = ["rock", "paper", "scissors", "bomb"]

def validmove(player, move):
    if move not in moves:
        return False
    if move == "bomb":
        if player == "user" and state["userbomb"]:
            return False
        if player == "bot" and state["botbomb"]:
            return False
    return True

def botmove():
    options = ["rock", "paper", "scissors"]
    if not state["botbomb"]:
        options.append("bomb")
    return random.choice(options)

def winner(user, bot):
    if user == bot:
        return "draw"
    if user == "bomb":
        return "user"
    if bot == "bomb":
        return "bot"
    rules = {
        "rock": "scissors",
        "scissors": "paper",
        "paper": "rock"
    }
    return "user" if rules[user] == bot else "bot"

print("Rock Paper Scissors Plus")
print("Best of 3 rounds")
print("Moves: rock paper scissors bomb")
print("Bomb can be used once")

while state["round"] <= 3:
    print("\nRound", state["round"])
    user = input("Your move: ").lower().strip()

    if not validmove("user", user):
        print("Invalid move. Round wasted.")
        state["round"] += 1
        continue

    bot = botmove()
    print("Bot move:", bot)

    if user == "bomb":
        state["userbomb"] = True
    if bot == "bomb":
        state["botbomb"] = True

    w = winner(user, bot)

    if w == "user":
        state["user"] += 1
        print("You win the round")
    elif w == "bot":
        state["bot"] += 1
        print("Bot wins the round")
    else:
        print("Round draw")

    state["round"] += 1
    print("Score You:", state["user"], "Bot:", state["bot"])

print("\nGame Over")
if state["user"] > state["bot"]:
    print("Final Result: YOU WIN")
elif state["bot"] > state["user"]:
    print("Final Result: BOT WINS")
else:
    print("Final Result: DRAW")